---
# meta/qb.yml file for nrser.js
# 
# qb settings for this role. see README.md for more info.
#

# description of the role to show in it's help output.
description: null

# prefix for role variables
var_prefix: null

# how to get a default for `dir` if it's not provided as the only
# positional argument. if a positional argument is provided it will
# override the method defined here.
# 
# options:
# 
# -   null
#     -   require the value on the command line.
# -   git_root
#     -   use the git root fof the directory that the `qb` command is invoked
#         from. useful for 'project-centric' commands so they can be invoked
#         from anywhere in the repo.
# -   cwd
#     -   use the directory the `qb` command is invoked form.
# -   {exe: PATH}
#     -   invoke an execuable, passing a JSON serialization of the options 
#         mapping their CLI names to values. path can be relative to role
#         directory.
default_dir: null

# default user to become for play
default_user: null

# set to false to not save options in .qb-options.yml files
save_options: true

options:
# - name: example
#   description: an example of a variable.
#   required: false
#   type: boolean # boolean (default) | string
#   short: e

- name: install
  description: run npm or yarn install
  type: boolean
  short: i

- name: yarn
  description: use yarn node package manager instead of npm
  type: boolean
  short: y

- include: qb.npm_package
  as: package
